### ISSUE TITLE
[每日信息流] 2023-01-28

### ISSUE THREAD

**Issue by zer0yu** [zer0yu/picker#63]
# 每日安全资讯（2023-01-28）

- SAP Blogs
  - [ ] [Extracting SAP Integrated Business Planning (IBP) data in SAP Signavio Process Intelligence via Odata service](https://blogs.sap.com/2023/01/27/extracting-sap-integrated-business-planning-ibp-data-in-sap-signavio-process-intelligence-via-odata-service/)
  - [ ] [Incorporating Diversity into Supplier Management](https://blogs.sap.com/2023/01/27/incorporating-diversity-into-supplier-management/)
  - [ ] [Experience the Energy Movement with SAP and Intel at DistribuTech 2023](https://blogs.sap.com/2023/01/27/experience-the-energy-movement-with-sap-and-intel-at-distributech-2023/)
  - [ ] [Previous SAP SuccessFactors Community users – Important Step for Login](https://blogs.sap.com/2023/01/27/previous-sap-successfactors-community-users-important-step-for-login/)
  - [ ] [SAP BTP Innobytes – January 2023](https://blogs.sap.com/2023/01/27/sap-btp-innobytes-january-2023/)
  - [ ] [Data Privacy and You](https://blogs.sap.com/2023/01/27/data-privacy-and-you/)
  - [ ] [Governance, Risk, and Compliance (GRC) with SAP S/4HANA Cloud 2302, Public Edition](https://blogs.sap.com/2023/01/27/governance-risk-and-compliance-grc-with-sap-s-4hana-cloud-2302-public-edition/)
  - [ ] [What’s new in the H2 Release: SAP SuccessFactors Work Zone? For starters, UX enhancements.](https://blogs.sap.com/2023/01/27/whats-new-in-the-h2-release-sap-successfactors-work-zone-for-starters-ux-enhancements./)
  - [ ] [DRC Colombia:  Medios Magnéticos — plazos de envios 2023](https://blogs.sap.com/2023/01/27/drc-colombia-medios-magneticos-plazos-de-envios-2023/)
- SecWiki News
  - [ ] [SecWiki News 2023-01-27 Review](http://www.sec-wiki.com/?2023-01-27)
- 博客
  - [ ] [ssh key type](https://dyrnq.com/ssh-key-type/)
- Twitter @Florian Roth ⚡
  - [ ] [RT 𝔅͛𝔯͛𝔦͛𝔞͛𝔫͛ ͛𝔚͛𝔥͛𝔢͛𝔩͛𝔱͛𝔬͛𝔫͛:](https://twitter.com/brianwhelton/status/1619082231846150151)
  - [ ] [Re @keydet89 @deadvolvo Good old gorillas … but I have to admit that I liked Tank Wars much more](https://twitter.com/cyb3rops/status/1619081393073700864)
  - [ ] [😐 reminds me of DEVICE=C:\Windows\himem.sys](https://twitter.com/cyb3rops/status/1619057748876066816)
  - [ ] [I thought it's a good idea to maintain information regarding the Detection Rule License (DRL) in a separate repository - very permissive license for d...](https://twitter.com/cyb3rops/status/1619046217354297371)
  - [ ] [RT Joe Stocker: Microsoft Defender for Office, Horror Story. A thread. (1/5) On Wednesday at 6:00 PM CST, Customer’s primary domain name is suddenly ...](https://twitter.com/ITguySoCal/status/1619043179168407552)
  - [ ] [Re @tomgoldsteincs @ditrizna I wouldn't align AI with today's way of schooling. I'd align schooling to a world of AIs.](https://twitter.com/cyb3rops/status/1619032271259897860)
  - [ ] [Re @pmelson @MalGamy12 @0xbahaa @nu11charb @hasherezade @th3_protoCOL @kienbigmummy @ale_sp_brazil @Maxmal @ffforward @1ZRR4H @Kostastsale @binaryz0ne...](https://twitter.com/cyb3rops/status/1619031504050438144)
  - [ ] [RT Hilko Bengen / @hillu@infosec.exchange: Just released v0.5.1 of Laurel, the #linux #auditd plugin event post-processing plugin that generates usefu...](https://twitter.com/_hillu/status/1619025672432939008)
  - [ ] [We've decided to share the #YARA rules to detect malicious #OneNote documents / attachments (.one) - as seen in #Phishing attacks - with the community...](https://twitter.com/cyb3rops/status/1619004667186511873)
  - [ ] [RT Christopher Peacock: Day 48 #100DaysofSigma Stop those pesky OneNote files before a user can open them with the OneNote Attachment File Dropped In ...](https://twitter.com/SecurePeacock/status/1618970834043023362)
  - [ ] [RT ESET Research: #BREAKING On January 25th #ESETResearch discovered a new cyberattack in 🇺🇦 Ukraine. Attackers deployed a new wiper we named #S...](https://twitter.com/ESETresearch/status/1618960022150729728)
  - [ ] [This reads like "Killnet hits government, airports, banks with DDoS attacks ... and .. well, nothing really happened." I can confirm. Nothing happened...](https://twitter.com/cyb3rops/status/1618946968147087362)
  - [ ] [I wonder when #AI starts reading LinkedIn profiles and sending job offers](https://twitter.com/cyb3rops/status/1618935173315448834)
  - [ ] [Re @John_Fokker @vxunderground](https://twitter.com/cyb3rops/status/1618900910452928512)
  - [ ] [RT ariaupdated: YES!! The #UpdatePolicy CSP page is now updated to show which policies should be used for what and which are legacy policies we don't ...](https://twitter.com/ariaupdated/status/1618875885771427840)
- Data Breach
  - [ ] [BlackCat Ransomware gang stole secret military data from an industrial explosives manufacturer](https://securityaffairs.com/141409/data-breach/blackcat-ransomware-solar-industries-india.html)
- Files ≈ Packet Storm
  - [ ] [Debian Security Advisory 5328-1](https://packetstormsecurity.com/files/170773/dsa-5328-1.txt)
  - [ ] [Razer Synapse 3.7.0731.072516 Local Privilege Escalation](https://packetstormsecurity.com/files/170772/SYSS-2022-047.txt)
  - [ ] [Red Hat Security Advisory 2023-0483-01](https://packetstormsecurity.com/files/170771/RHSA-2023-0483-01.txt)
  - [ ] [OpenSCAP Libraries 1.3.7](https://packetstormsecurity.com/files/170770/openscap-1.3.7.tar.gz)
  - [ ] [Ubuntu Security Notice USN-5822-2](https://packetstormsecurity.com/files/170769/USN-5822-2.txt)
  - [ ] [Micro Focus GroupWise Session ID Disclosure](https://packetstormsecurity.com/files/170768/TRSA-2203-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0476-01](https://packetstormsecurity.com/files/170767/RHSA-2023-0476-01.txt)
  - [ ] [Debian Security Advisory 5329-1](https://packetstormsecurity.com/files/170766/dsa-5329-1.txt)
  - [ ] [Red Hat Security Advisory 2023-0481-01](https://packetstormsecurity.com/files/170765/RHSA-2023-0481-01.txt)
  - [ ] [Apple Security Advisory 2023-01-24-1](https://packetstormsecurity.com/files/170764/APPLE-SA-2023-01-24-1.txt)
  - [ ] [PHPJabbers Car Rental Script 3.0 SQL Injection](https://packetstormsecurity.com/files/170763/carrentalscript30-sql.txt)
  - [ ] [Red Hat Security Advisory 2023-0208-01](https://packetstormsecurity.com/files/170762/RHSA-2023-0208-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0210-01](https://packetstormsecurity.com/files/170761/RHSA-2023-0210-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0479-01](https://packetstormsecurity.com/files/170760/RHSA-2023-0479-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0470-01](https://packetstormsecurity.com/files/170759/RHSA-2023-0470-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0469-01](https://packetstormsecurity.com/files/170758/RHSA-2023-0469-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0471-01](https://packetstormsecurity.com/files/170757/RHSA-2023-0471-01.txt)
- Twitter @Nicolas Krassas
  - [ ] [2 Federal Agencies Hacked With Remote Monitoring](https://twitter.com/Dinosn/status/1619040817901080578)
  - [ ] [Hacker accused of having stolen personal data of all Austrians and more](https://twitter.com/Dinosn/status/1619040203179720704)
  - [ ] [US Hacks Back Against Hive Ransomware Crew](https://twitter.com/Dinosn/status/1619040171097485312)
  - [ ] [Critical RCE Lexmark Printer Bug Has Public Exploit](https://twitter.com/Dinosn/status/1619040118802911234)
  - [ ] [Experts Uncover the Identity of Mastermind Behind Golden Chickens Malware Service](https://twitter.com/Dinosn/status/1618983105712500737)
  - [ ] [You got Domain Admin, now what?](https://twitter.com/Dinosn/status/1618974808359989249)
  - [ ] [MX Takeovers Automated | Subdomain Takeover](https://twitter.com/Dinosn/status/1618974605271760897)
  - [ ] [Pre-Auth RCE on OpenEMR: Using a rogue MySQL server to steal your health data](https://twitter.com/Dinosn/status/1618974273716236289)
  - [ ] [BlueHound - Tool That Helps Blue Teams Pinpoint The Security Issues That Actually Matter](https://twitter.com/Dinosn/status/1618974213150474247)
  - [ ] [A Guide to Phishing Attacks](https://twitter.com/Dinosn/status/1618974047068631041)
  - [ ] [Researchers Discover New PlugX Malware Variant Spreading via Removable USB Devices](https://twitter.com/Dinosn/status/1618973345533538309)
  - [ ] [GUAC - Aggregates Software Security Metadata Into A High Fidelity Graph Database](https://twitter.com/Dinosn/status/1618868990750892032)
  - [ ] [What Happens When Crypto Derivatives Crash](https://twitter.com/Dinosn/status/1618868904620851205)
  - [ ] [An unfaithful employee leaked Yandex source code repositories](https://twitter.com/Dinosn/status/1618868202234327040)
  - [ ] [US offers $10M bounty for Hive ransomware links to foreign governments](https://twitter.com/Dinosn/status/1618868124660686848)
  - [ ] [Bitwarden password vaults targeted in Google ads phishing attack](https://twitter.com/Dinosn/status/1618867219261431809)
  - [ ] [SaaS RootKit Exploits Hidden Rules in Microsoft 365](https://twitter.com/Dinosn/status/1618867179964997632)
  - [ ] [Easy XSSHunter Discord Alerts](https://twitter.com/Dinosn/status/1618862393832144897)
- Hacker Noon
  - [ ] [The Glory of REST: Is It Really That Glorious?](https://hackernoon.com/the-glory-of-rest-is-it-really-that-glorious?source=rss)
  - [ ] [AI Drug Discovery: How It’s Changing the Game](https://hackernoon.com/ai-drug-discovery-how-its-changing-the-game?source=rss)
  - [ ] [How Will User Experience Change in 2023?](https://hackernoon.com/how-will-user-experience-change-in-2023?source=rss)
  - [ ] [5 GitHub Repositories That Will Change Your Life](https://hackernoon.com/5-github-repositories-that-will-change-your-life?source=rss)
  - [ ] [An Intro to NIM: The Python-Like Programming Language Used By Malicious Ransomware Developers](https://hackernoon.com/an-intro-to-nim-the-python-like-programming-language-used-by-malicious-ransomware-developers?source=rss)
  - [ ] [The Noonification: Unity 2023.1 Introduces Awaitable Class (1/27/2023)](https://hackernoon.com/1-27-2023-noonification?source=rss)
  - [ ] [9 Underrated Startup Podcasts You Should Start Listening to in 2023](https://hackernoon.com/9-underrated-startup-podcasts-you-should-start-listening-to-in-2023?source=rss)
  - [ ] [Behavioral Economics: Growth Hackers' Secret Weapon](https://hackernoon.com/behavioral-economics-growth-hackers-secret-weapon?source=rss)
  - [ ] [Microsoft‘s Big AI Ambitions Go Beyond Just OpenAI and ChatGPT](https://hackernoon.com/microsofts-big-ai-ambitions-go-beyond-just-openai-and-chatgpt?source=rss)
  - [ ] [How to Get Started with TypeScript](https://hackernoon.com/how-to-get-started-with-typescript?source=rss)
  - [ ] [Generate WordPress Posts Automatically with Python](https://hackernoon.com/generate-wordpress-posts-automatically-with-python?source=rss)
  - [ ] [If AI Could Help You Take Control of Your Life, Would You Let It?](https://hackernoon.com/if-ai-could-help-you-take-control-of-your-life-would-you-let-it?source=rss)
  - [ ] [Composable Commerce Was Supposed to Be the Future, What Happened?](https://hackernoon.com/composable-commerce-was-supposed-to-be-the-future-what-happened?source=rss)
  - [ ] [How to Generate a List of All Token Transactions Within a Wallet](https://hackernoon.com/how-to-generate-a-list-of-all-token-transactions-within-a-wallet?source=rss)
  - [ ] [An Introduction to Regenerative Finance (ReFi)](https://hackernoon.com/an-introduction-to-regenerative-finance-refi?source=rss)
  - [ ] [The Palmer Method of Business Writing: Lesson 136](https://hackernoon.com/the-palmer-method-of-business-writing-lesson-136?source=rss)
  - [ ] [21 API Monitoring Tools That Will Make You a Developer Superhero in 2023!](https://hackernoon.com/21-api-monitoring-tools-that-will-make-you-a-developer-superhero-in-2023?source=rss)
  - [ ] [Investment Management Software Streamlines Processes for Real Estate Investors and Managers](https://hackernoon.com/investment-management-software-streamlines-processes-for-real-estate-investors-and-managers?source=rss)
- InfoSec Write-ups - Medium
  - [ ] [Easy XSSHunter Discord Alerts](https://infosecwriteups.com/easy-xsshunter-discord-alerts-33fcff24a8f7?source=rss----7b722bfd1b8d---4)
  - [ ] [MX Takeovers Automated | Subdomain Takeover](https://infosecwriteups.com/mx-takeovers-automated-subdomain-takeover-64e658fc4fb7?source=rss----7b722bfd1b8d---4)
  - [ ] [Biggest Cybersecurity Threats in 2023](https://infosecwriteups.com/biggest-cybersecurity-threats-in-2023-353d77af8d11?source=rss----7b722bfd1b8d---4)
  - [ ] [Data Science meets Cyber Security](https://infosecwriteups.com/data-science-meets-cyber-security-41d5f567b163?source=rss----7b722bfd1b8d---4)
  - [ ] [You got Domain Admin, now what?](https://infosecwriteups.com/you-got-domain-admin-now-what-aab749c4200d?source=rss----7b722bfd1b8d---4)
  - [ ] [3 practical steps to learn AWS security in 2023](https://infosecwriteups.com/3-practical-steps-to-learn-aws-security-in-2023-3919624a7949?source=rss----7b722bfd1b8d---4)
  - [ ] [Easy XSSHunter Express Setup Script](https://infosecwriteups.com/easy-xsshunter-express-setup-script-d5a66039f7b6?source=rss----7b722bfd1b8d---4)
- unSafe.sh - 不安全
  - [ ] [警方称一荷兰黑客获得了几乎所有奥地利人的个人数据](https://buaq.net/go-146873.html)
  - [ ] [Yandex 称前雇员泄露源代码](https://buaq.net/go-146874.html)
  - [ ] [英特尔砍掉了 Pathfinder for RISC-V 项目](https://buaq.net/go-146875.html)
  - [ ] [解决Debian系统环境中文乱码的问题 检查设置UTF-8编码](https://buaq.net/go-146862.html)
  - [ ] [Burp Suite roadmap update: January 2023](https://buaq.net/go-146871.html)
  - [ ] [Mitigating RBAC-Based Privilege Escalation in Popular Kubernetes Platforms](https://buaq.net/go-146860.html)
  - [ ] [The Good, the Bad and the Ugly in Cybersecurity – Week 4](https://buaq.net/go-146858.html)
  - [ ] [.prt and .asm file reverse engineered](https://buaq.net/go-146857.html)
  - [ ] [Software risks and technical debt: The role of process in determining good software](https://buaq.net/go-146859.html)
  - [ ] [【计算机视觉】OpenCV 4高级编程与项目实战（Python版）【4】：通道详解](https://buaq.net/go-146870.html)
  - [ ] [BlueHound - Tool That Helps Blue Teams Pinpoint The Security Issues That Actually Matter](https://buaq.net/go-146849.html)
  - [ ] [Packetlabs Ltd delivers advanced testing capabilities with Burp Suite Certified Practitioners](https://buaq.net/go-146848.html)
  - [ ] [AI in cybersecurity: The good, the bad, and the ugly](https://buaq.net/go-146840.html)
- Security Boulevard
  - [ ] [Clarification of Obligations for the Use of Online Tracking Technologies by HIPAA Covered Entities and Business Associates](https://securityboulevard.com/2023/01/clarification-of-obligations-for-the-use-of-online-tracking-technologies-by-hipaa-covered-entities-and-business-associates/)
  - [ ] [CBA AND FIDO: One, Other, or Both?](https://securityboulevard.com/2023/01/cba-and-fido-one-other-or-both/)
  - [ ] [VMware vRealize Log Insight VMSA-2023-0001 IOCs](https://securityboulevard.com/2023/01/vmware-vrealize-log-insight-vmsa-2023-0001-iocs/)
  - [ ] [Chainguard Unveils Memory-Safe Linux Distribution](https://securityboulevard.com/2023/01/chainguard-unveils-memory-safe-linux-distribution/)
  - [ ] [‘Hive’ Russian Ransomware Gang Shut Down by FBI, DoJ, Europol, Bundeskriminalamt, et al](https://securityboulevard.com/2023/01/hive-ransomware-seized-richixbw/)
  - [ ] [The Top 8 Phishlabs Competitors for 2023](https://securityboulevard.com/2023/01/the-top-8-phishlabs-competitors-for-2023/)
  - [ ] [Comic Agilé – Mikkel Noe-Nygaard, Luxshan Ratnarav – ‘#226 – Black, White and Gray’](https://securityboulevard.com/2023/01/comic-agile-mikkel-noe-nygaard-luxshan-ratnarav-226-black-white-and-gray/)
  - [ ] [Love Is in the Air — And So Are API Threats](https://securityboulevard.com/2023/01/love-is-in-the-air-and-so-are-api-threats/)
  - [ ] [Exploring Killnet’s Social Circles](https://securityboulevard.com/2023/01/exploring-killnets-social-circles/)
  - [ ] [Hate Group Pressures American School Library to Censor Holocaust](https://securityboulevard.com/2023/01/hate-group-pressures-american-school-library-to-censor-holocaust/)
- 嘶吼 RoarTalk – 回归最本质的信息安全,互联网安全新媒体,4hou.com
  - [ ] [Docker Hub存储库隐藏了1650多个恶意容器](https://www.4hou.com/posts/N1A8)
- Sploitus.com Exploits RSS Feed
  - [ ] [Micro Focus GroupWise Session ID Disclosure exploit](https://sploitus.com/exploit?id=PACKETSTORM:170768&utm_source=rss&utm_medium=rss)
  - [ ] [PHPJabbers Car Rental Script 3.0 SQL Injection exploit](https://sploitus.com/exploit?id=PACKETSTORM:170763&utm_source=rss&utm_medium=rss)
  - [ ] [Razer Synapse 3.7.0731.072516 Local Privilege Escalation exploit](https://sploitus.com/exploit?id=PACKETSTORM:170772&utm_source=rss&utm_medium=rss)
  - [ ] [Exploit for Use After Free in Linux Linux Kernel exploit](https://sploitus.com/exploit?id=9CBE87B2-5ADC-5DA9-972B-132F77839B5F&utm_source=rss&utm_medium=rss)
- Hex Rays
  - [ ] [Igor’s Tip of the Week #125: Structure fields representation](https://hex-rays.com/blog/igors-tip-of-the-week-125-structure-fields-representation/)
- Tenable Blog
  - [ ] [Sandworm APT Deploys New SwiftSlicer Wiper Using Active Directory Group Policy](https://www.tenable.com/blog/sandworm-apt-deploys-new-swiftslicer-wiper-using-active-directory-group-policy)
  - [ ] [Cybersecurity Snapshot: IoT Vendors Fail at Vulnerability Disclosures, While Cyber Threats Again Top Business Risks](https://www.tenable.com/blog/cybersecurity-snapshot-iot-vendors-fail-at-vulnerability-disclosures-while-cyber-threats-again)
- Dark Reading
  - [ ] [Why Most Companies Still Don’t Know What’s on Their Network](https://www.darkreading.com/risk/why-most-companies-still-don-t-know-what-s-on-their-network)
  - [ ] [On Data Privacy Day, Organizations Fail Data Privacy Expectations](https://www.darkreading.com/omdia/on-data-privacy-day-organizations-fail-data-privacy-expectations)
  - [ ] [Critical RCE Lexmark Printer Bug Has Public Exploit](https://www.darkreading.com/cloud/critical-rce-lexmark-printer-bug-has-public-exploit)
  - [ ] [Google: Influence Operator Dragonbridge Floods Social Media in Sprawling Cyber Campaign](https://www.darkreading.com/vulnerabilities-threats/google-influence-operator-dragonbridge-floods-social-media-sprawling-cyber-campaign)
  - [ ] [How Noob Website Hackers Can Become Persistent Threats](https://www.darkreading.com/attacks-breaches/noob-hackers-become-persistent-threats)
  - [ ] [3 Ways ChatGPT Will Change Infosec in 2023](https://www.darkreading.com/vulnerabilities-threats/3-ways-chatgpt-will-change-infosec-in-2023)
- Dhole Moments
  - [ ] [Dogwhistles and Other Falsehoods Uttered About Furries](https://soatok.blog/2023/01/27/dogwhistles-and-other-falsehoods-uttered-about-furries/)
- Twitter @hakivvi
  - [ ] [Re @pwntester very informing post, thank you.](https://twitter.com/hakivvi/status/1619096149197033472)
  - [ ] [RT Alvaro Muñoz 🇺🇦: Had some fun with OGNL sandboxes last year. Read how I bypassed Atlassian Confluence and Struts ones in my latest blog post](https://twitter.com/pwntester/status/1619090515915587588)
- FreeBuf网络安全行业门户
  - [ ] [LOL源代码被盗，暗网100万拍卖](https://www.freebuf.com/news/355784.html)
- Bug Bounty in InfoSec Write-ups on Medium
  - [ ] [Easy XSSHunter Discord Alerts](https://infosecwriteups.com/easy-xsshunter-discord-alerts-33fcff24a8f7?source=rss----7b722bfd1b8d--bug_bounty)
  - [ ] [Easy XSSHunter Express Setup Script](https://infosecwriteups.com/easy-xsshunter-express-setup-script-d5a66039f7b6?source=rss----7b722bfd1b8d--bug_bounty)
- Application Security Blog
  - [ ] [Software risks and technical debt: The role of process in determining good software](https://www.synopsys.com/blogs/software-security/software-risks-technical-debt/)
- 奇客Solidot–传递最新科技情报
  - [ ] [警方称一荷兰黑客获得了几乎所有奥地利人的个人数据](https://www.solidot.org/story?sid=73962)
  - [ ] [Yandex 称前雇员泄露源代码](https://www.solidot.org/story?sid=73961)
  - [ ] [英特尔砍掉了 Pathfinder for RISC-V 项目](https://www.solidot.org/story?sid=73960)
- EdOverflow
  - [ ] [Adding security headers to your SvelteKit application](https://edoverflow.com/2023/sveltekit-security-headers/)
- 黑海洋 - WIKI
  - [ ] [解决Debian系统环境中文乱码的问题 检查设置UTF-8编码](https://blog.upx8.com/3202)
- 丁爸情报分析师的工具箱
  - [ ] [【研究报告】乌克兰战争200天的初步教训](https://mp.weixin.qq.com/s?__biz=MzI2MTE0NTE3Mw==&mid=2651134697&idx=1&sn=8dad74a0d2f6d09a33c0bb02242265e4&chksm=f1af6dd3c6d8e4c509bb73f28dfdea7b2365c031310e9f8e4dae3ddd2f07ed03521fbc232aa8&scene=58&subscene=0#rd)
- The Daily Swig | Cybersecurity news and views
  - [ ] [Deserialized web security roundup: ‘Catastrophic cyber events’, another T-Mobile breach, more LastPass problems](https://portswigger.net/daily-swig/deserialized-web-security-roundup-catastrophic-cyber-events-another-t-mobile-breach-more-lastpass-problems)
  - [ ] [Facebook two-factor authentication bypass issue patched](https://portswigger.net/daily-swig/facebook-two-factor-authentication-bypass-issue-patched)
- 网安寻路人
  - [ ] [数据隐私法和竞争法的交叉：若干新进展](https://mp.weixin.qq.com/s?__biz=MzIxODM0NDU4MQ==&mid=2247498775&idx=1&sn=890d85c053cc3759255e27fe9b0a5326&chksm=97e941fda09ec8ebb424510e0d8d6cee6237f77630915e14ab2cdb23ed8de0fa4021a04b726d&scene=58&subscene=0#rd)
- 情报分析师
  - [ ] [【北约认知战资料集】《认知主导未来》（118页）](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650524518&idx=1&sn=69efea793f2db544637e4850ee24404c&chksm=8716e52db0616c3b747652fde75fe07ae4dbd142b56da9ca066a8825c6f4ecd444b388a264ed&scene=58&subscene=0#rd)
  - [ ] [信息图：对美国安全至关重要的50种矿物（附美国地质调查局报告）](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650524518&idx=2&sn=a059ef9f6585ffed44a44e6c0e3b3d1b&chksm=8716e52db0616c3b011b7b3b89f134fe56a47b9f5b70b081ce53b15d991c41192ef884c5f822&scene=58&subscene=0#rd)
- 极客公园
  - [ ] [硅谷都在裁员，奈飞却在增长](https://mp.weixin.qq.com/s?__biz=MTMwNDMwODQ0MQ==&mid=2652981770&idx=1&sn=cf9c8fe1c78088f8a3ec4a6eb75e153b&chksm=7e5437bc4923beaa185b78aac25d4656c2e86fe51d6bcf0d0615ccb848062228181ef6da8ac5&scene=58&subscene=0#rd)
  - [ ] [《满江红》否认抄袭；智能手机出货量创下有史以来最大跌幅；AI 律师开发者遭入狱威胁 | 极客早知道](https://mp.weixin.qq.com/s?__biz=MTMwNDMwODQ0MQ==&mid=2652981754&idx=1&sn=5153468bf34df34e556dd9687ed81b8d&chksm=7e54344c4923bd5a7b5c68972b2aeacd20bb9e4d82ab7e17c8ec5e63c4cadfa481d74e6689c5&scene=58&subscene=0#rd)
- 嘶吼专业版
  - [ ] [StrongPity APT组织使用木马化的telegram软件假冒Shagle 应用程序发起攻击](https://mp.weixin.qq.com/s?__biz=MzI0MDY1MDU4MQ==&mid=2247556797&idx=1&sn=e0bea5ebfcc1c1ba08b32861a223a5b6&chksm=e915ce87de6247912c934b411d01e970c781c3b30b2dbe32952242db5eb552ce3459bbc337a3&scene=58&subscene=0#rd)
  - [ ] [Black Basta最近一次的攻击事件分析](https://mp.weixin.qq.com/s?__biz=MzI0MDY1MDU4MQ==&mid=2247556797&idx=2&sn=c721885066dab480c4fcd1b53c35ef77&chksm=e915ce87de624791151180aeeecb19d6a27b55b7717f0cc21cccaa52a1d84c9d0615df5d88ee&scene=58&subscene=0#rd)
- 解道jdon.com
  - [ ] [软件架构的简单发展介绍](https://www.jdon.com/64729.html)
  - [ ] [实践中的模块化单体 | Foojay.io](https://www.jdon.com/64728.html)
  - [ ] [业务网格上的上下文映射 - Alberto](https://www.jdon.com/64727.html)
  - [ ] [Java 21实现了性能改进](https://www.jdon.com/64726.html)
- Skywind Inside
  - [ ] [使用 LIBLR 解析带注释的 JSON](https://www.skywind.me/blog/archives/2677)
- SEO 网站优化及网站推广
  - [ ] [Google Optimize 下线退休](https://seo.g2soft.net/2023/01/27/google-optimize-retired.html)
  - [ ] [从 Wix 的角度来看搜索引擎优化](https://seo.g2soft.net/2023/01/26/seo-of-wix.html)
- 卢昌海个人主页
  - [ ] [最新微博：2023 年 1 月 26 日](https://www.changhai.org/articles/miscellaneous/blog/202301.php#latest)
- Frytea's Blog
  - [ ] [每次离开的时候才会特别想家](https://blog.frytea.com/archives/734/)
  - [ ] [macOS 安装 Emacs](https://blog.frytea.com/archives/733/)
- 满五的博客
  - [ ] [浮尘](https://blog.aeilot.top/2023/01/27/dust/)
- 某岛
  - [ ] [RM2k3 机能增强 —— EasyRPG Player 魔改版](https://www.shuizilong.com/house/archives/rm2k3-%e6%9c%ba%e8%83%bd%e5%a2%9e%e5%bc%ba-easyrpg-player-%e9%ad%94%e6%94%b9%e7%89%88/)
- 一大加贝
  - [ ] [Ed Sheeran - Perfect](https://tianheg.xyz/posts/ed-sheeran-perfect/)
- luozhiyun`s Blog
  - [ ] [[聊聊算法]并查集原理及实战](https://www.luozhiyun.com/archives/751)
  - [ ] [[聊聊算法]拓扑排序原理及实战](https://www.luozhiyun.com/archives/748)
- 年华转瞬
  - [ ] [Pensieve: 2301](https://xiaket.github.io/2023/pensieve-2301.html)
- 二丫讲梵
  - [ ] [学习周刊-总第91期-2023年第04周](https://wiki.eryajf.net/pages/644c4d/)
- Super Blog
  - [ ] [使用 Arc 浏览器自定义网页](https://superpung.com/arc-boost/)
- 游研社
  - [ ] [【红白机N合1】这部制作堪比《忍龙》却饱受冷遇的FC大作，你见过吗？](https://alioss.yystv.cn/doc/10394/89eaa088a1f7a02c85adaaf445a25019.mp4)
- 文艺数学君
  - [ ] [北邮人论坛十大_2023_01_27](https://mathpretty.com/15550.html)
- Mukti
  - [ ] [每周分享第198期](https://feizhaojun.com/?p=3676)
- 拾月
  - [ ] [启用中文昵称：拾月](https://www.skyue.com/23012719.html)
- ZkeqのCoding日志
  - [ ] [归档｜CSDN 图片上传接口 & 开发历程](https://icodeq.com/2023/d7a2d5e64c0f/)
- 开飞机的老张
  - [ ] [JavaScript的深拷贝和浅拷贝](https://kaifeiji.cc/post/deep-copy-vs-shallow-copy-in-javascript/)
- Yunfeng's Simple Blog
  - [ ] [手机上看arxiv上论文的方法](http://vra.github.io/2023/01/27/arxiv-on-mobile/)
- 个人生活分享
  - [ ] [长隆所见 Day3](https://fxpai.com/zhanglongsuojian-day3/)
- Finisky Garden
  - [ ] [Hexo环境变量区分生产环境](https://finisky.github.io/how-to-set-hexo-env/)
- 恋学的小🐻
  - [ ] [GitHub CLI 命令行工具（gh)](https://nsddd.top/archives/gh)
