### ISSUE TITLE
[每日信息流] 2023-01-03

### ISSUE THREAD

**Issue by zer0yu** [zer0yu/picker#8]
# 每日安全资讯（2023-01-03）

- ふるつき
  - [ ] [Schoofのアルゴリズムで楕円曲線の位数を求める - yoshicamp参加記(1)](https://furutsuki.hatenablog.com/entry/2023/01/02/233804)
- SAP Blogs
  - [ ] [0.1 + 0.2 does not equal 0.3](https://blogs.sap.com/2023/01/02/0.1-0.2-does-not-equal-0.3/)
  - [ ] [Preventing Lateral Movement in SAP Environments](https://blogs.sap.com/2023/01/02/preventing-lateral-movement-in-sap-environments/)
  - [ ] [[SAP BTP Onboarding Series] – Step-by-Step guide to activate your SAP Build Work Zone, Advanced Edition](https://blogs.sap.com/2023/01/02/sap-btp-onboarding-series-step-by-step-guide-to-activate-your-sap-build-work-zone-advanced-edition/)
  - [ ] [HANA Analytical Privileges in SAP DWC – Part 1](https://blogs.sap.com/2023/01/02/hana-analytical-privileges-in-sap-dwc-part-1/)
  - [ ] [Task state and Requirement State in SAP Cloud ALM](https://blogs.sap.com/2023/01/02/task-state-and-requirement-state-in-sap-cloud-alm/)
  - [ ] [SAP Community Call: Achieve Excellent Accuracy with Next-Level Document Information Extraction](https://blogs.sap.com/2023/01/02/sap-community-call-achieve-excellent-accuracy-with-next-level-document-information-extraction/)
  - [ ] [Sales kits in S/4 Hana Cloud Order to Cash process ( ERLA, LUMF, CPFH, DISH ) – Scope item 31Q](https://blogs.sap.com/2023/01/02/sales-kits-in-s-4-hana-cloud-order-to-cash-process-erla-lumf-cpfh-dish-scope-item-31q/)
  - [ ] [Expose Calculation view as a service via OData in HANA XSA using Web IDE](https://blogs.sap.com/2023/01/02/expose-calculation-view-as-a-service-via-odata-in-hana-xsa-using-web-ide/)
- Twitter @bytehx
  - [ ] [RT Trickest: Gather a list of 2.5 MILLION hostnames belonging to public bug bounty programs from Inventory 🤹](https://twitter.com/trick3st/status/1609939838865637379)
  - [ ] [RT Nicolas Krassas: Make URL path combinations using a wordlist](https://twitter.com/Dinosn/status/1609791790739070977)
- Twitter @Florian Roth ⚡
  - [ ] [Re @ali_alwashali](https://twitter.com/cyb3rops/status/1610043711647551488)
  - [ ] [Re and I meant any Exchange server and not just the known-vulnerable ones Every exchange server has been vulnerable at one point and attackers could h...](https://twitter.com/cyb3rops/status/1610029865868181504)
  - [ ] [Re @Vert1cal_ I recommend - 010editor - ImHex](https://twitter.com/cyb3rops/status/1609992203174285313)
  - [ ] [I highly recommend scanning On-Prem MS Exchange instances with our free scanner THOR Lite We still try to channel out all Exchange exploitation relate...](https://twitter.com/cyb3rops/status/1609937393158701059)
  - [ ] [Re @ryoichi_tanaka It's a Linux reverse shell .. I see them frequently with IPv4 addresses ... This one was different](https://twitter.com/cyb3rops/status/1609935622931636227)
  - [ ] [First, I though: "Omg, they finally start using IPv6!" Then I realised that it's just a MAC address (lmao)](https://twitter.com/cyb3rops/status/1609904916776030210)
  - [ ] [Re @Vert1cal_ Also read this :](https://twitter.com/cyb3rops/status/1609885640870576130)
  - [ ] [Re @ulfposh](https://twitter.com/cyb3rops/status/1609884854358786049)
  - [ ] [RT Security Joes: HEADS UP - New #RaspberryRobin version found targeting Europe major financial institutes:](https://twitter.com/SecurityJoes/status/1609825477140553731)
  - [ ] [RT Objective-See Foundation: Just published our (7th) annual "The Mac Malware of <Year>" report for 2022 🥳 It's 70(!) pages of technical details co...](https://twitter.com/objective_see/status/1609824759432507392)
  - [ ] [RT Have I Been Pwned: New breach: Deezer had 229M unique email addresses breached from a 2019 backup and shared online in late 2022. Data included nam...](https://twitter.com/haveibeenpwned/status/1609754235557777408)
  - [ ] [RT Sylvain Bruyere: Excited to share that while working @AirbusCERT ❤, I was fortunate enough to write a #VBScript/VBA #deobfuscator proto, based on ...](https://twitter.com/sylvainbruyere/status/1609701297778737152)
- unSafe.sh - 不安全
  - [ ] [LineageOS 20 发布](https://buaq.net/go-143803.html)
  - [ ] [如果外星人联络人类，谁决定我们接下来怎么做？](https://buaq.net/go-143804.html)
  - [ ] [源码分析 kubernetes coredns 插件服务发现及解析的实现原理](https://buaq.net/go-143815.html)
  - [ ] [古代猫咪与人类一同迁徙到世界各地](https://buaq.net/go-143805.html)
  - [ ] [逾四十个国家和地区提供数字游牧民签证](https://buaq.net/go-143806.html)
  - [ ] [Schoofのアルゴリズムで楕円曲線の位数を求める - yoshicamp参加記(1)](https://buaq.net/go-143797.html)
  - [ ] [OrBit: analysis of a Linux dedicated malware](https://buaq.net/go-143792.html)
  - [ ] [【计算机视觉】OpenCV 4高级编程与项目实战（Python版）【1】：图像处理基础](https://buaq.net/go-143811.html)
  - [ ] [gallery-dl – 支持 1400+ 网站的开源图片批量下载工具](https://buaq.net/go-143793.html)
  - [ ] [Subparse - Modular Malware Analysis Artifact Collection And Correlation Framework](https://buaq.net/go-143779.html)
  - [ ] [超强截图贴图工具 Snipaste 专业版优惠](https://buaq.net/go-143778.html)
  - [ ] [#!/usr/bin/env 的意义](https://buaq.net/go-143773.html)
  - [ ] [CVE-2022-38627: A journey through SQLite Injection to compromise the whole enterprise building](https://buaq.net/go-143761.html)
- Security Boulevard
  - [ ] [USENIX Security ’22 – Ruiwen He, Xiaoyu Ji, and Xinfeng Li, Yushi Cheng, Wenyuan Xu ’OK, Siri” Or “Hey, Google”: Evaluating Voiceprint Distinctiveness Via Content-based PROLE Score’](https://securityboulevard.com/2023/01/usenix-security-22-ruiwen-he-xiaoyu-ji-and-xinfeng-li-yushi-cheng-wenyuan-xu-ok-siri-or-hey-google-evaluating-voiceprint-distinctiveness-via-content-based-prole-score/)
  - [ ] [Randall Munroe’s XKCD ‘New Year’s Eve Party’](https://securityboulevard.com/2023/01/randall-munroes-xkcd-new-years-eve-party/)
  - [ ] [6 Cybersecurity Trends to Keep an Eye on in the New Year](https://securityboulevard.com/2023/01/6-cybersecurity-trends-to-keep-an-eye-on-in-the-new-year/)
  - [ ] [Why You and Your Team Should Attend Ontic Summit 2023](https://securityboulevard.com/2023/01/why-you-and-your-team-should-attend-ontic-summit-2023/)
  - [ ] [USENIX Security ’22 – Jeffrey Young, Song Liao, Long Cheng,  Hongxin Hu, Huixing Deng ’SkillDetective: Automated Policy-Violation Detection Of Voice Assistant Applications In The Wild’](https://securityboulevard.com/2023/01/usenix-security-22-jeffrey-young-song-liao-long-cheng-hongxin-hu-huixing-deng-skilldetective-automated-policy-violation-detection-of-voice-assistant-applications-in-the-wild/)
  - [ ] [Best of 2022: 1Password’s Blue Ocean Strategy](https://securityboulevard.com/2023/01/1passwords-blue-ocean-strategy/)
  - [ ] [A risk-focused approach to security control prioritization](https://securityboulevard.com/2023/01/a-risk-focused-approach-to-security-control-prioritization/)
  - [ ] [Best of 2022: Best online .apk virus scanners – Hackernet](https://securityboulevard.com/2023/01/best-online-apk-virus-scanners-hackernet/)
  - [ ] [July Cyber Roundup](https://securityboulevard.com/2023/01/july-cyber-roundup/)
  - [ ] [October Cyber Roundup](https://securityboulevard.com/2023/01/october-cyber-roundup/)
- Files ≈ Packet Storm
  - [ ] [GNUnet P2P Framework 0.19.1](https://packetstormsecurity.com/files/170360/gnunet-0.19.1.tar.gz)
  - [ ] [Packet Storm New Exploits For 2022](https://packetstormsecurity.com/files/170359/2022-exploits.tgz)
  - [ ] [Packet Storm New Exploits For December, 2022](https://packetstormsecurity.com/files/170358/202212-exploits.tgz)
  - [ ] [Chrome Synchronous Mojo Use-After-Free](https://packetstormsecurity.com/files/170357/GS20230102143415.tgz)
  - [ ] [crewjam/saml Signature Bypass](https://packetstormsecurity.com/files/170356/GS20230102143226.tgz)
  - [ ] [EuskalHack Security Congress VI Call For Papers](https://packetstormsecurity.com/files/170355/CFP_EuskalHack2023_EN.txt)
  - [ ] [Oracle Unified Audit Policy Bypass](https://packetstormsecurity.com/files/170354/oracleuap-bypass.txt)
  - [ ] [Red Hat Security Advisory 2023-0005-01](https://packetstormsecurity.com/files/170353/RHSA-2023-0005-01.txt)
  - [ ] [Red Hat Security Advisory 2023-0004-01](https://packetstormsecurity.com/files/170352/RHSA-2023-0004-01.txt)
  - [ ] [Debian Security Advisory 5310-1](https://packetstormsecurity.com/files/170351/dsa-5310-1.txt)
  - [ ] [Debian Security Advisory 5309-1](https://packetstormsecurity.com/files/170350/dsa-5309-1.txt)
  - [ ] [Debian Security Advisory 5308-1](https://packetstormsecurity.com/files/170349/dsa-5308-1.txt)
  - [ ] [Debian Security Advisory 5307-1](https://packetstormsecurity.com/files/170348/dsa-5307-1.txt)
- Twitter @Nicolas Krassas
  - [ ] [Reverse Engineering and Exploiting an IoT bug](https://twitter.com/Dinosn/status/1610022727003377665)
  - [ ] [Subparse - Modular Malware Analysis Artifact Collection And Correlation Framework](https://twitter.com/Dinosn/status/1610015198026383360)
  - [ ] [Google Home Speakers Were Vulnerable To Eavesdropping Hackers](https://twitter.com/Dinosn/status/1610014937522356225)
  - [ ] [Inside the 8086 processor's instruction prefetch circuitry](https://twitter.com/Dinosn/status/1610014832480366592)
  - [ ] [RedZei Chinese Scammers Targeting Chinese Students in the U.K.](https://twitter.com/Dinosn/status/1610014755674288128)
  - [ ] [GitHub - kitabisa/teler-waf: teler-waf is a Go HTTP middleware that provide teler IDS functionality with teler IDS to protect against web-based attack...](https://twitter.com/Dinosn/status/1609856834998788100)
  - [ ] [CVE-2022-38627: A journey through SQLite Injection to compromise the whole enterprise building](https://twitter.com/Dinosn/status/1609855843738034178)
  - [ ] [REcollapse: black-box regex fuzzing to bypass validations and discover normalizations in WebApps](https://twitter.com/Dinosn/status/1609855599180910593)
  - [ ] [GRR Rapid Response: remote live forensics for incident response](https://twitter.com/Dinosn/status/1609821984124280833)
  - [ ] [Java code inspector for web vulnerability scan, building method call chains and emulate stack frame for analysis (JavaWeb vulnerability audit tool, bu...](https://twitter.com/Dinosn/status/1609792290821931008)
  - [ ] [Subdomains analysis and generation tool. Reveal the hidden!](https://twitter.com/Dinosn/status/1609792035447504896)
  - [ ] [Make URL path combinations using a wordlist](https://twitter.com/Dinosn/status/1609791790739070977)
  - [ ] [Google to Pay $29.5 Million to Settle Lawsuits Over User Location Tracking](https://twitter.com/Dinosn/status/1609791054840053760)
  - [ ] [Deezer - 229,037,936 breached accounts](https://twitter.com/Dinosn/status/1609779425289150464)
  - [ ] [Ransomware gang cloned victim’s website to leak stolen data](https://twitter.com/Dinosn/status/1609765738734034947)
  - [ ] [Lockbit apologized for the attack on the SickKids pediatric hospital and releases a free decryptor](https://twitter.com/Dinosn/status/1609761241773244416)
  - [ ] [Reflective DLL Injection explained](https://twitter.com/Dinosn/status/1609760645632921600)
- Hacker Noon
  - [ ] [Top 10 Web3 Events You Should Attend in Jan-May 2023](https://hackernoon.com/top-10-web3-events-you-should-attend-in-jan-may-2023?source=rss)
  - [ ] [Meet the Writer: HackerNoon's Contributor Tanyo, Founder and Web3 Gaming Connoisseur](https://hackernoon.com/meet-the-writer-hackernoons-contributor-tanyo-founder-and-web3-gaming-connoisseur?source=rss)
  - [ ] [Instant Gratification Layers Are the Future, Not Blockchains - BOG#003](https://hackernoon.com/instant-gratification-layers-are-the-future-not-blockchains-bog003?source=rss)
  - [ ] [Meet Noonies 2022 Winner: Omri Hurwitz Startup Blogger of The Year](https://hackernoon.com/meet-noonies-2022-winner-omri-hurwitz-startup-blogger-of-the-year?source=rss)
  - [ ] [Breakpoints: The Massive Power They Have Explained](https://hackernoon.com/breakpoints-the-massive-power-they-have-explained?source=rss)
  - [ ] [Is Data Monetization Dead?](https://hackernoon.com/is-data-monetization-dead?source=rss)
  - [ ] [Why Do Investors Say "No"?](https://hackernoon.com/why-do-investors-say-no?source=rss)
  - [ ] [5 Tips for Optimizing Your Landing Pages for Mobile](https://hackernoon.com/5-tips-for-optimizing-your-landing-pages-for-mobile?source=rss)
  - [ ] [Meet the Writer: Contributor Nicolas Fränkel, Head of Developer Advocacy on Apache APISIX](https://hackernoon.com/meet-the-writer-contributor-nicolas-frankel-head-of-developer-advocacy-on-apache-apisix?source=rss)
  - [ ] [Crypto Shadow Banking Explained: Credit for Market Makers](https://hackernoon.com/crypto-shadow-banking-explained-credit-for-market-makers?source=rss)
  - [ ] [Winners Crowned as Everscale Hackathon Wraps up](https://hackernoon.com/winners-crowned-as-everscale-hackathon-wraps-up?source=rss)
  - [ ] [The Noonification: Cloud Phishing: New Tricks and the Crown Jewel (1/2/2023)](https://hackernoon.com/1-2-2023-noonification?source=rss)
  - [ ] [ChatGPT is a Huge Win for Conversational AI Companies (and Their Customers) — Here's Why](https://hackernoon.com/chatgpt-is-a-huge-win-for-conversational-ai-companies-and-their-customers-heres-why?source=rss)
  - [ ] [Press Mentions For Your Brand: A Growth Marketer's How-To](https://hackernoon.com/press-mentions-for-your-brand-a-growth-marketers-how-to?source=rss)
  - [ ] [Gravity Simulation With Unity DOTS 1.0](https://hackernoon.com/gravity-simulation-with-unity-dots-10?source=rss)
  - [ ] [Real-World Examples of Using Design Patterns in Modern PHP](https://hackernoon.com/real-world-examples-of-using-design-patterns-in-modern-php?source=rss)
  - [ ] [How to Change Your Email Signature in Outlook](https://hackernoon.com/how-to-change-your-email-signature-in-outlook?source=rss)
  - [ ] [How This TikTok Ad Received 3.7 Million Views](https://hackernoon.com/how-this-tiktok-ad-received-37-million-views?source=rss)
  - [ ] [The Secret Behind Market-Making Superpowers is in the Liquidity SLAs](https://hackernoon.com/the-secret-behind-market-making-superpowers-is-in-the-liquidity-slas?source=rss)
  - [ ] [5 Macro-Trends That Will Impact Businesses Over the Next 10 Years](https://hackernoon.com/5-macro-trends-that-will-impact-businesses-over-the-next-10-years?source=rss)
- Tenable Blog
  - [ ] [Tenable Cyber Watch: What Do Our Experts Predict for 2023?](https://www.tenable.com/blog/tenable-cyber-watch-what-do-our-experts-predict-for-2023)
- Verne in GitHub
  - [ ] [J3455 主板无法使用 PCIe 扩展 SATA 启动系统解决](https://einverne.github.io/post/2023/01/j3455-itx-cannot-boot-csm.html)
- CXSECURITY Database RSS Feed - CXSecurity.com
  - [ ] [COURIER DEPRIXA V2.5 Backdoor Account Vulnerability](https://cxsecurity.com/issue/WLB-2023010002)
  - [ ] [Oracle Unified Audit Policy Bypass](https://cxsecurity.com/issue/WLB-2023010001)
- InfoSec Write-ups - Medium
  - [ ] [‍IW Weekly #40: Open Redirection Vulnerability, Misconfigured Jira, Bugs in Red Bull, ChatGPT…](https://infosecwriteups.com/iw-weekly-40-open-redirection-vulnerability-misconfigured-jira-bugs-in-red-bull-chatgpt-ea5ac454d0cf?source=rss----7b722bfd1b8d---4)
  - [ ] [CVE-2022-38627: A journey through SQLite Injection to compromise the whole enterprise building](https://infosecwriteups.com/cve-2022-38627-a-journey-through-sqlite-injection-to-compromise-the-whole-enterprise-building-15cebd072ed6?source=rss----7b722bfd1b8d---4)
- Sploitus.com Exploits RSS Feed
  - [ ] [Oracle Unified Audit Policy Bypass exploit](https://sploitus.com/exploit?id=PACKETSTORM:170354&utm_source=rss&utm_medium=rss)
  - [ ] [Exploit for Command Injection in Cacti exploit](https://sploitus.com/exploit?id=9D2C3CDB-7544-50CA-8581-92EC5E1291A2&utm_source=rss&utm_medium=rss)
- 嘶吼 RoarTalk – 回归最本质的信息安全,互联网安全新媒体,4hou.com
  - [ ] [Google Home智能音箱漏洞可监听用户会话](https://www.4hou.com/posts/zlGy)
  - [ ] [Win11 23H2的发布会让彻底杜绝KASLR绕过吗？](https://www.4hou.com/posts/03x5)
- FreeBuf网络安全行业门户
  - [ ] [FreeBuf早报 | 谷歌将支付近三千万美元和解位置跟踪；加拿大矿业公司遭攻击后关闭](https://www.freebuf.com/news/354087.html)
- 雷神众测
  - [ ] [团建日｜雷神众测白帽团建日记](https://mp.weixin.qq.com/s?__biz=MzI0NzEwOTM0MA==&mid=2652501142&idx=1&sn=663e7688d55808d7ea446e822ca01276&chksm=f2585725c52fde33141e36da3953fbbfde8950fe5aba88f986d9a859fe444ed93ad8c57844ec&scene=58&subscene=0#rd)
- HackerNews
  - [ ] [黑客可以监听用户对话！谷歌 Home 音箱出现安全问题](https://hackernews.cc/archives/42976)
- 杨龙
  - [ ] [#!/usr/bin/env 的意义](https://www.yanglong.pro/usr-bin-env-%e7%9a%84%e6%84%8f%e4%b9%89/)
- 青衣十三楼飞花堂
  - [ ] [cby的日常(before 2022.10.15)](https://mp.weixin.qq.com/s?__biz=MzUzMjQyMDE3Ng==&mid=2247486389&idx=1&sn=3fd25ad7eda36db67c74eb8b1af63da3&chksm=fab2c88acdc5419c031484d183381937103c573535f72a2a0a0a4eaa46640f95860e39b65163&scene=58&subscene=0#rd)
- Bug Bounty in InfoSec Write-ups on Medium
  - [ ] [CVE-2022-38627: A journey through SQLite Injection to compromise the whole enterprise building](https://infosecwriteups.com/cve-2022-38627-a-journey-through-sqlite-injection-to-compromise-the-whole-enterprise-building-15cebd072ed6?source=rss----7b722bfd1b8d--bug_bounty)
- 安全小飞侠
  - [ ] [一个普通网安从业人员的2022](https://mp.weixin.qq.com/s?__biz=MzAwMzAwOTQ5Nw==&mid=2650941721&idx=1&sn=b42e6641025fe0003fdc8990bc74bf79&chksm=813737afb640beb96e84ee243a01628f75a1955d6b74c652b3d95db7ef362eb00e397c322c6c&scene=58&subscene=0#rd)
- 极客公园
  - [ ] [ChatGPT，正在动摇谷歌的商业长城](https://mp.weixin.qq.com/s?__biz=MTMwNDMwODQ0MQ==&mid=2652979738&idx=1&sn=d7d2e714ff6527f1a53f84fd952a2f20&chksm=7e543fac4923b6ba21e0e15f017637cf788dc7758507b8adcb62584af0af1b0d420a246e46da&scene=58&subscene=0#rd)
  - [ ] [「蔚小理」2022 年交付量曝光；马斯克，资产缩水 2000 亿美元第一人；英特尔、高通力推主动散热芯片 | 极客早知道](https://mp.weixin.qq.com/s?__biz=MTMwNDMwODQ0MQ==&mid=2652979736&idx=1&sn=c55f34645821cddcd0b26484a6f77031&chksm=7e543fae4923b6b8bf912cd5796617fbb7c4eafb7dcc160c1fe099228c5c5e985542b1b32412&scene=58&subscene=0#rd)
- 奇客Solidot–传递最新科技情报
  - [ ] [LineageOS 20 发布](https://www.solidot.org/story?sid=73787)
  - [ ] [如果外星人联络人类，谁决定我们接下来怎么做？](https://www.solidot.org/story?sid=73786)
  - [ ] [古代猫咪与人类一同迁徙到世界各地](https://www.solidot.org/story?sid=73785)
  - [ ] [逾四十个国家和地区提供数字游牧民签证](https://www.solidot.org/story?sid=73784)
- 情报分析师
  - [ ] [最新研究报告：苹果正在跟踪你](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650521775&idx=1&sn=a34e4317647f6237d204dcd3285358a8&chksm=8716eee4b06167f2b7346f8754e3148ed56fd2b200e5a66caa1f44a230b3b2457fd99e93cfb4&scene=58&subscene=0#rd)
  - [ ] [美国各地的警察使用大规模位置跟踪工具进行绕过搜查令](https://mp.weixin.qq.com/s?__biz=MzA3Mjc1MTkwOA==&mid=2650521775&idx=2&sn=04f17aa1728cc7700db92ea3c04d78dd&chksm=8716eee4b06167f20bd61b3cc84e4ad7e79a86aa54e7bb3f128d2bd7bbc9682df7304f9bb65e&scene=58&subscene=0#rd)
- @Kurisu
  - [ ] [2022 Summary -&gt; 2023](https://kuricat.com/articles/2022-summary-2023-qx7yi)
- Frytea's Blog
  - [ ] [2022 年博客经营报告](https://blog.frytea.com/archives/717/)
- Limboy
  - [ ] [富爸爸穷爸爸](https://limboy.me/books/rich-dad-poor-dad/)
- 解道jdon.com
  - [ ] [leptos: 使用 Rust 快速构建 Web 应用](https://www.jdon.com/64218.html)
  - [ ] [什么是区块链中的”图graph“？](https://www.jdon.com/64217.html)
  - [ ] [使用基于科学的工具建立或打破习惯 - Huberman](https://www.jdon.com/64216.html)
  - [ ] [关于如何以及为什么需要函数式编程？ - Merrick](https://www.jdon.com/64215.html)
  - [ ] [一切都使用 Postgres](https://www.jdon.com/64214.html)
  - [ ] [什么是以太坊生态系统中的ABI？](https://www.jdon.com/64213.html)
- 卢昌海个人主页
  - [ ] [《微言录》 (三集) 第二版自序](https://www.changhai.org/articles/books/Ebook13_Preface2.php)
  - [ ] [最新微博：2023 年 1 月 1 日 (2)](https://www.changhai.org/articles/miscellaneous/blog/202301.php#d0101B)
- Panda Home
  - [ ] [异度神剑终极版](https://old-panda.com/2023/01/01/review-of-xenoblade-chronicles-definitive-edition/?utm_source=rss&utm_medium=rss&utm_campaign=review-of-xenoblade-chronicles-definitive-edition)
- 一大加贝
  - [ ] [LC 1. Two Sum](https://tianheg.xyz/posts/lc-1-two-sum/)
  - [ ] [LC 9. Palindrome Number](https://tianheg.xyz/posts/lc-9-palindrome-number/)
  - [ ] [月读（2023年1月）](https://tianheg.xyz/posts/monthly-2023-01/)
  - [ ] [浏览器工作原理](https://tianheg.xyz/posts/how-browsers-work/)
- 渚碧
  - [ ] [「仿制药的真相」读后的几点感想](https://jubeny.com/2023/01/some-thoughts-about-bottle-of-lies/)
- 二丫讲梵
  - [ ] [学习周刊-总第87期-2022年第52周](https://wiki.eryajf.net/pages/ba509d/)
- 张小凯的博客
  - [ ] [memos部署总结](https://jasonkayzk.github.io/2023/01/02/memos%E9%83%A8%E7%BD%B2%E6%80%BB%E7%BB%93/)
  - [ ] [阳了之后的感受以及新的生活](https://jasonkayzk.github.io/2023/01/02/%E9%98%B3%E4%BA%86%E4%B9%8B%E5%90%8E%E7%9A%84%E6%84%9F%E5%8F%97%E4%BB%A5%E5%8F%8A%E6%96%B0%E7%9A%84%E7%94%9F%E6%B4%BB/)
- 文艺数学君
  - [ ] [北邮人论坛十大_2023_01_02](https://mathpretty.com/15422.html)
- Tinyfool的个人网站
  - [ ] [万能的ChatGPT真有智能了么？一篇文章让你彻底搞懂ChatGPT-人类是怎么训练出了一只聪明的莎士比亚的猴子](https://codechina.org/2023/01/chatgpt-ai-human-principle-and-limitation/)
- This Cute World
  - [ ] [2022 年年终总结](https://thiscute.world/posts/2022-summary/)
- DGideas' Blog
  - [ ] [与光——我的二零二二年](https://dgideas.net/2023/my-2022/)
- 金属成色
  - [ ] [人工反馈的强化学习](https://lowin.li/2023/01/02/ren-gong-fan-kui-de-qiang-hua-xue-xi/)
- ShineKid
  - [ ] [飞](https://shinekid.com/2023/01/flying/)
- 程序员的喵
  - [ ] [我的 2022](http://catcoding.me/p/2022-summary/)
- yiyun's Blog
  - [ ] [30天学会 React | 笔记](https://moeci.com/posts/%E5%88%86%E7%B1%BB-Web/30-days-of-react-notebook/)
- 开飞机的老张
  - [ ] [Javascript获取当前时间戳](https://kaifeiji.cc/post/get-the-current-timestamp-in-javascript/)
  - [ ] [掌握Javascript-基础篇](https://kaifeiji.cc/post/mastering-js-fundamentals/)
- jdhao's digital space
  - [ ] [感染 omicron 记录](https://jdhao.github.io/2023/01/02/i-got-covid/)
- 烟草的香味
  - [ ] [拜占庭将军问题](https://hujingnb.com/archives/881)
- Airing 的小屋
  - [ ] [2022，平安喜乐](https://me.ursb.me/archives/2022.html)
- Tw93 的博客
  - [ ] [什么是比较好的低代码产品](https://tw93.fun/2023-01-02/low-code.html)
- 时间的朋友
  - [ ] [31. Next Permutation](https://blog.storycn.cn/posts/2023/01/31.-next-permutation/)
- 偕臧
  - [ ] [小米路由器 R4A 刷原生 OpenWrt 后的风景](https://ifmet.cn/posts/880ce1ac/)
- 工劳小报｜工劳快讯
  - [ ] [2022年十大劳动关键词：闭环、封条、清退、露宿、热射病、裁员、失业、停运、坠亡、火灾](https://newsletter2.laborinfocn.com/2022summary/)
- Cubik 的小站
  - [ ] [2022 年 12 月总结 (2022 年终总结？)](https://www.cubik65536.top/2022-12-MonthJournal/)
- Pseudoyu
  - [ ] [摄影集 #02 - Moment In Peking (The Autumn)](https://www.pseudoyu.com/zh/2023/01/02/moment_in_peking_the_autumn/)
